# Generated by Django 6.1.1 on 2026-09-16 09:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message="Phone number must contain 7 to 15 digits, optionally starting with '+'.", regex='^\\+?[0-9]{7,15}$')])),
                ('date_of_birth', models.DateField()),
                ('course', models.CharField(choices=[('CSE', 'Computer Science Engineering'), ('ECE', 'Electronics & Communication Engineering'), ('MECH', 'Mechanical Engineering'), ('CIVIL', 'Civil Engineering'), ('EEE', 'Electrical & Electronics Engineering'), ('IT', 'Information Technology'), ('OTHER', 'Other')], default='OTHER', max_length=10)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('address', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
